<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Book extends \App\Models\Entities\Book implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'idb', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'name', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'authors', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'description', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'image', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'users', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'genres', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'reviews', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'quotes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'idb', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'name', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'authors', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'description', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'image', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'users', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'genres', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'reviews', '' . "\0" . 'App\\Models\\Entities\\Book' . "\0" . 'quotes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Book $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdb()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdb();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdb', []);

        return parent::getIdb();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthors($authors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthors', [$authors]);

        return parent::setAuthors($authors);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthors', []);

        return parent::getAuthors();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function addGenre(\App\Models\Entities\Genre $genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGenre', [$genre]);

        return parent::addGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGenre(\App\Models\Entities\Genre $genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGenre', [$genre]);

        return parent::removeGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenres', []);

        return parent::getGenres();
    }

    /**
     * {@inheritDoc}
     */
    public function addReview(\App\Models\Entities\Review $review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReview', [$review]);

        return parent::addReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReview(\App\Models\Entities\Review $review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReview', [$review]);

        return parent::removeReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviews', []);

        return parent::getReviews();
    }

    /**
     * {@inheritDoc}
     */
    public function addQuote(\App\Models\Entities\Quote $quote)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuote', [$quote]);

        return parent::addQuote($quote);
    }

    /**
     * {@inheritDoc}
     */
    public function addUsers(\App\Models\Entities\Userbooks $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsers', [$user]);

        return parent::addUsers($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQuote(\App\Models\Entities\Quote $quote)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQuote', [$quote]);

        return parent::removeQuote($quote);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuotes', []);

        return parent::getQuotes();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsers(\App\Models\Entities\Userbooks $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsers', [$user]);

        return parent::removeUsers($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getBooks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBooks', []);

        return parent::getBooks();
    }

}
